name: devlens_example
description: Example app for DevLens
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  devlens:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true